/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import com.model.dBaseAccount;
import java.awt.Color;
import java.awt.PopupMenu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FinalBooking extends javax.swing.JFrame {

    /**
     * Creates new form FinalBooking
     */
    ResultSet rs;
    Vector v1;
    double totalfare;
    public FinalBooking() {
        initComponents();
        Color backgroundcolor = new Color(200,204,255);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
        setResizable(true);      
    }
    
    public void  flightBookingDetails(Vector v,int op) throws SQLException           
    {
      String departtime=null,departfare=null,arrivaltime=null,returntime=null,arrivalrtime=null,returnfare=null; 
      double dfare=0,rfare=0;
      v1=v;
      returnFinalPanel.setVisible(false);
      lbldepartureflight.setText(String.valueOf(v.get(0))+" to "+String.valueOf(v.get(1)));
      lbldcode.setText(String.valueOf(v.get(4)));
      DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
      lbldeparturedate.setText(String.valueOf(df.format(v.get(2))));
      dBaseAccount dba = new dBaseAccount();
      rs = dba.departFlight(String.valueOf(v.get(4)));
      
      while(rs.next()==true)
      {
          departtime = rs.getString("departtime");
          arrivaltime = rs.getString("arrivaltime");
          departfare = rs.getString("fare");
      }
      lbldeparturetime.setText(departtime);
      lblarrivaltime.setText(arrivaltime);
      lbldeparturefare.setText(departfare+"/-");
     
      dfare = Double.parseDouble(departfare);
      
      
      //return
      if(op==2)
      {
          returnFinalPanel.setVisible(true);
      lblreturnflight.setText(String.valueOf(v.get(1))+" to "+String.valueOf(v.get(0)));
      lblrcode.setText(String.valueOf(v.get(5)));
      DateFormat dfr = new SimpleDateFormat("dd-MM-yyyy");
      lblreturndate.setText(String.valueOf(dfr.format(v.get(3))));
      rs = dba.departFlight(String.valueOf(v.get(5)));
      while(rs.next()==true)
      {
          returntime = rs.getString("departtime");
          arrivalrtime = rs.getString("arrivaltime");
          returnfare = rs.getString("fare");
      }
      lblreturntime.setText(returntime);
      lblrarrivaltime.setText(arrivalrtime);
      lblreturnfare.setText(returnfare+"/-");
      rfare = Double.parseDouble(returnfare);
      }
      
      totalfare = 1.1*(dfare+rfare);
      lbltotalfare.setText(""+totalfare+"/-");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        departureFinalPanel = new javax.swing.JPanel();
        lblorigin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbldcode = new javax.swing.JLabel();
        lbldeparturedate = new javax.swing.JLabel();
        lbldeparturetime = new javax.swing.JLabel();
        lbldeparturefare = new javax.swing.JLabel();
        lbldepartureflight = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblarrivaltime = new javax.swing.JLabel();
        returnFinalPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblrcode = new javax.swing.JLabel();
        lblreturndate = new javax.swing.JLabel();
        lblreturntime = new javax.swing.JLabel();
        lblreturnfare = new javax.swing.JLabel();
        lblreturnflight = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblrarrivaltime = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbltotalfare = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        salutation = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Complete your Booking");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mobile No.");

        firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        firstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblorigin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Flight Code:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Departure Date:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Departure Time:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Fare:");

        lbldcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldcode.setText("jLabel19");

        lbldeparturedate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldeparturedate.setText("jLabel20");

        lbldeparturetime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldeparturetime.setText("jLabel21");

        lbldeparturefare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldeparturefare.setText("jLabel22");

        lbldepartureflight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldepartureflight.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Arrival Time:");

        lblarrivaltime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblarrivaltime.setText("jLabel7");

        javax.swing.GroupLayout departureFinalPanelLayout = new javax.swing.GroupLayout(departureFinalPanel);
        departureFinalPanel.setLayout(departureFinalPanelLayout);
        departureFinalPanelLayout.setHorizontalGroup(
            departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departureFinalPanelLayout.createSequentialGroup()
                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(departureFinalPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lbldepartureflight))
                    .addGroup(departureFinalPanelLayout.createSequentialGroup()
                        .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(departureFinalPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(lblorigin)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, departureFinalPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblarrivaltime)
                            .addComponent(lbldcode)
                            .addComponent(lbldeparturedate)
                            .addComponent(lbldeparturefare)
                            .addComponent(lbldeparturetime))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        departureFinalPanelLayout.setVerticalGroup(
            departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departureFinalPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbldepartureflight, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblorigin)
                .addGap(26, 26, 26)
                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbldcode))
                .addGap(18, 18, 18)
                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbldeparturedate))
                .addGap(18, 18, 18)
                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbldeparturetime))
                .addGap(18, 18, 18)
                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblarrivaltime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(departureFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeparturefare)
                    .addComponent(jLabel14))
                .addGap(48, 48, 48))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Flight Code:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Return Date:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Return Time:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Fare:");

        lblrcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrcode.setText("jLabel23");

        lblreturndate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblreturndate.setText("jLabel24");

        lblreturntime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblreturntime.setText("jLabel25");

        lblreturnfare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblreturnfare.setText("jLabel26");

        lblreturnflight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblreturnflight.setText("jLabel29");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Arrival Time:");

        lblrarrivaltime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrarrivaltime.setText("jLabel8");

        javax.swing.GroupLayout returnFinalPanelLayout = new javax.swing.GroupLayout(returnFinalPanel);
        returnFinalPanel.setLayout(returnFinalPanelLayout);
        returnFinalPanelLayout.setHorizontalGroup(
            returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnFinalPanelLayout.createSequentialGroup()
                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnFinalPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnFinalPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblrcode))
                            .addGroup(returnFinalPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblreturndate))
                            .addGroup(returnFinalPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblreturntime))
                            .addGroup(returnFinalPanelLayout.createSequentialGroup()
                                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblrarrivaltime)
                                    .addComponent(lblreturnfare)))))
                    .addGroup(returnFinalPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblreturnflight)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        returnFinalPanelLayout.setVerticalGroup(
            returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnFinalPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblreturnflight)
                .addGap(26, 26, 26)
                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblrcode))
                .addGap(18, 18, 18)
                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblreturndate)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblreturntime))
                .addGap(18, 18, 18)
                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblrarrivaltime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(returnFinalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreturnfare)
                    .addComponent(jLabel18))
                .addGap(54, 54, 54))
        );

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Total Fare ( including GST10% ):");

        lbltotalfare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalfare.setText("jLabel28");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Complete Booking");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Salutation");

        salutation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salutation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mrs" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel2)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(firstname))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(lastName))
                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(departureFinalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(returnFinalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotalfare))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButton1)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(firstname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnFinalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureFinalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lbltotalfare))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int x=0;
        dBaseAccount db = new dBaseAccount();
        try {
            x = db.insertdata(String.valueOf(v1.get(0)),String.valueOf(v1.get(1)), String.valueOf(v1.get(4)),String.valueOf(v1.get(5)),String.valueOf(totalfare),String.valueOf(salutation.getSelectedItem()), String.valueOf(firstName.getText()),String.valueOf(lastName.getText()),String.valueOf(contact.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(x==1)
            JOptionPane.showMessageDialog(null,"BOOKING DONE SUCCESSFULLY");
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JPanel departureFinalPanel;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lblarrivaltime;
    private javax.swing.JLabel lbldcode;
    private javax.swing.JLabel lbldeparturedate;
    private javax.swing.JLabel lbldeparturefare;
    private javax.swing.JLabel lbldepartureflight;
    private javax.swing.JLabel lbldeparturetime;
    private javax.swing.JLabel lblorigin;
    private javax.swing.JLabel lblrarrivaltime;
    private javax.swing.JLabel lblrcode;
    private javax.swing.JLabel lblreturndate;
    private javax.swing.JLabel lblreturnfare;
    private javax.swing.JLabel lblreturnflight;
    private javax.swing.JLabel lblreturntime;
    private javax.swing.JLabel lbltotalfare;
    private javax.swing.JPanel returnFinalPanel;
    private javax.swing.JComboBox<String> salutation;
    // End of variables declaration//GEN-END:variables
}
